- name: Create Key and Show Base64
        run: |
          # Използвайте вашата парола 'MY_PASSWORD' тук
          keytool -genkeypair -v \
            -keystore nutriplan.keystore \
            -alias nutriplan \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass "MY_PASSWORD" \
            -keypass "MY_PASSWORD" \
            -dname "CN=NutriPlan" \
            -noprompt
          
          echo "------------------------------------------------"
          base64 -w 0 nutriplan.keystore
          echo -e "\n------------------------------------------------"
