name: Key Generator
on: workflow_dispatch

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Keystore
        run: |
          keytool -genkeypair -v \
            -keystore nutriplan.keystore \
            -alias nutriplan \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass "${{ secrets.KEYSTORE_PASSWORD }}" \
            -keypass "${{ secrets.KEY_PASSWORD }}" \
            -dname "CN=NutriPlan" \
            -noprompt
          echo "--- COPY START ---"
          base64 -w 0 nutriplan.keystore
          echo -e "\n--- COPY END ---"
